import {StyleSheet} from 'react-native';

export const globalStyles = StyleSheet.create({
  containerIntro: {
    flex: 1,
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: '#403F3E',
  },
  mainTextIntro: {
    fontSize: 24,
    fontFamily: 'monospace',
    color: '#fff',
    fontWeight: 'bold',
  },
  textIntro: {
    fontFamily: 'monospace',
    fontSize: 21,
    color: '#fff',
  },
  buttonIntro: {
    width: 260,
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  buttonTextIntro: {
    fontFamily: 'monospace',
    textAlign: 'center',
    fontSize: 20,
    padding: 20,
    color: '#403F3E',
  },
  containerModal: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'stretch',
    backgroundColor: '#403F3E',
    paddingTop: 25,
  },
  titleModal: {
    fontFamily: 'monospace',
    fontSize: 28,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
  },
  textInfoModal: {
    fontFamily: 'monospace',
    color: '#fff',
    fontSize: 22,
    alignSelf: 'center',
  },
  itemModal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'transparent',
    width: 300,
    padding: 20,
    borderRadius: 10,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  detailModal: {
    fontFamily: 'monospace',
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    alignSelf: 'center',
  },
  buttonClose: {
    textAlign: 'center',
    padding: 15,
    width: 150,
    alignSelf: 'center',
    marginHorizontal: 10,
    marginVertical: 20,
    backgroundColor: '#E1341E',
    fontFamily: 'monospace',
    color: '#fff',
    fontSize: 20,
    borderRadius: 10,
  },
  itemComponent: {
    flex:1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap:'wrap',
    backgroundColor: '#9A95A6',
    padding: 20,
    borderRadius: 10,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  detailComponent: {
    fontFamily: 'monospace',
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    alignSelf: 'center',
  },
  containerSearch: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#403F3E',
    paddingTop: 21,
  },
  inputSearch: {
    borderWidth: 1,
    borderColor: '#fafefa',
    borderRadius: 5,
    padding: 10,
    margin: 10,
    fontFamily:"monospace",
    fontSize: 18,
    backgroundColor: '#fafefa',
    alignSelf: 'stretch',
  },
  buttonSearch: {
    width: 150,
    margin: 15,
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  buttonTextSearch: {
    textAlign: 'center',
    fontFamily:"monospace",
    fontSize: 18,
    padding: 12,
    color: '#403F3E',
  },
});
